name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Установка Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Авторизация в Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Деплой проекта
        run: railway up
